export const START_GET_PRODUCTS = 'START_GET_PRODUCTS';
export const SUCCES_GET_PRODUCTS = 'SUCCES_GET_PRODUCTS';
export const ERROR_GET_PRODUCTS = 'ERROR_GET_PRODUCTS';
export const START_GET_PRODUCT_DETAILS = 'START_GET_PRODUCT_DETAILS';
export const SUCCES_GET_PRODUCT_DETAILS = 'SUCCES_GET_PRODUCT_DETAILS';
export const ERROR_GET_PRODUCT_DETAILS = 'ERROR_GET_PRODUCT_DETAILS';
